services:
  bedrock-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bedrock-client-app
    container_name: bedrock_client
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=${AWS_REGION:-eu-central-1} # Valeur par défaut si non fournie dans .env
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
# Pour utiliser ce fichier docker-compose.yml :
# 1. Créez un fichier .env à la racine du projet avec vos variables d'environnement :
#    AWS_REGION=your_aws_region
#    AWS_ACCESS_KEY_ID=your_access_key_id
#    AWS_SECRET_ACCESS_KEY=your_secret_access_key
#    # AWS_SESSION_TOKEN=your_session_token # Optionnel

# 2. Exécutez la commande :
#    docker-compose up

# 3. Pour arrêter et supprimer les conteneurs :
#    docker-compose down
